In [1]:
import pandas as pd
import numpy as np
import sklearn

In [11]:
columns = ['item_id', 'movie_name', 'genre']
movie = pd.read_csv('./data/ml-10M100K/movies.dat', sep='::', names=columns)
movie = movie.drop(columns='genre').copy()
movie

C:\Users\Administrator\anaconda3\lib\site-packages\pandas\util\_decorators.py:311: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  return func(*args, **kwargs)

       item_id                          movie_name
0            1                    Toy Story (1995)
1            2                      Jumanji (1995)
2            3             Grumpier Old Men (1995)
3            4            Waiting to Exhale (1995)
4            5  Father of the Bride Part II (1995)
...        ...                                 ...
10676    65088              Bedtime Stories (2008)
10677    65091          Manhattan Melodrama (1934)
10678    65126                        Choke (2008)
10679    65130           Revolutionary Road (2008)
10680    65133      Blackadder Back & Forth (1999)

[10681 rows x 2 columns]

In [12]:
columns = ['user_id', 'item_id', 'rating', 'timestamp']
rating = pd.read_csv('./data/ml-10M100K/ratings.dat', sep='::', names=columns)
rating

C:\Users\Administrator\anaconda3\lib\site-packages\pandas\util\_decorators.py:311: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  return func(*args, **kwargs)

          user_id  item_id  rating  timestamp
0               1      122     5.0  838985046
1               1      185     5.0  838983525
2               1      231     5.0  838983392
3               1      292     5.0  838983421
4               1      316     5.0  838983392
...           ...      ...     ...        ...
10000049    71567     2107     1.0  912580553
10000050    71567     2126     2.0  912649143
10000051    71567     2294     5.0  912577968
10000052    71567     2338     2.0  912578016
10000053    71567     2384     2.0  912578173

[10000054 rows x 4 columns]

In [14]:
print(len(rating.item_id.unique()))
print(len(movie.item_id.unique()))

10677
10681

In [15]:
movies_data = pd.merge(rating, movie, on='item_id')

In [16]:
movies_data

,user_id,item_id,rating,timestamp,movie_name
0,1,122,5.0,838985046,Boomerang (1992)
1,139,122,3.0,974302621,Boomerang (1992)
2,149,122,2.5,1112342322,Boomerang (1992)
3,182,122,3.0,943458784,Boomerang (1992)
4,215,122,4.5,1102493547,Boomerang (1992)
...,...,...,...,...,...
10000049,67385,63481,3.5,1227499991,Soul Men (2008)
10000050,67542,63481,3.0,1227739303,Soul Men (2008)
10000051,67385,64652,2.0,1230900023,Delgo (2008)
10000052,69135,64427,4.0,1229529033,Much Ado About Something (2001)
10000053,70816,63662,4.0,1227531270,Where A Good Man Goes (Joi gin a long) (1999)

In [17]:
movies_data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 10000054 entries, 0 to 10000053
Data columns (total 5 columns):
 #   Column      Dtype
---  ------      -----
 0   user_id     int64
 1   item_id     int64
 2   rating      float64
 3   timestamp   int64
 4   movie_name  object
dtypes: float64(1), int64(3), object(1)
memory usage: 457.8+ MB

In [18]:
movies_data.isnull().sum()

user_id       0
item_id       0
rating        0
timestamp     0
movie_name    0
dtype: int64

In [19]:
rating_table = movies_data.pivot_table(values="rating",
                                   index="user_id",
                                   columns="movie_name",
                                   fill_value=0)

MemoryError: Unable to allocate 5.45 GiB for an array with shape (10460, 69878) and data type float64